# Configuration for GitHub Labeler
# This file defines which labels are automatically applied to pull requests
# based on the paths of files that are modified.

documentation:
  - '*.md'
  - 'docs/**'
  - 'README.md'
  - 'Project Description.txt'

github-actions:
  - '.github/**'
  - '.github/workflows/**'

dependencies:
  - 'package.json'
  - 'package-lock.json'
  - 'requirements.txt'
  - 'Pipfile'
  - 'Pipfile.lock'

python:
  - '**/*.py'

javascript:
  - '**/*.js'

typescript:
  - '**/*.ts'

html:
  - '**/*.html'

css:
  - '**/*.css'
  - '**/*.scss'

configuration:
  - '**/*.yml'
  - '**/*.yaml'
  - '**/*.json'
  - '**/*.toml'
  - '**/*.ini'
  - '**/*.conf'
