FROM nginx:alpine

# Copy Nginx Configuration
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Remove default nginx static assets
RUN rm -rf /usr/share/nginx/html/*

# Copy Pre-built React App
COPY dist /usr/share/nginx/html

# Expose Port
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
